### ISSUE TITLE
Make it available to all?

### ISSUE THREAD

**Issue by pconesa** [genisvalentin/scipion-em-WARPhole#2]
Hi @genisvale I've just discovered this, today. What a nice surprise!. It is always nice to other grow functionality.

I'm not sure if this is more an ad-hoc project or it could be generic enough for others to benefit from your effort.

If this is the case, let me, know. We usually assist in tweaking details that are hard to realize and not clear or missing in our documentation. But with a small effort,  it usually can be released to the wild.

We can add this to our automated testing tool, provided there is any test.

Well, take your time if this comes too early, but let me know how my suggestion works for you?

Streaming is hard. Do not doubt to ask for assistance. Also we can add you to our slack workspace for developers, so you get all developers to listen to you.

**Comment by genisvalentin** [comment]
Hi @pconesa 

Thanks for your encouragement! The plan is to share this tool with the world. 

At the moment the basic functionality is there, and I am running some tests internally.  I will soon write a post in the scipion users group for people to start playing with WARPhole.

I would also like to expand the tool a little bit, so indeed I requested access to the slack channel. I will need help with writing tests as well, since I am not a skilled developer.

**Comment by pconesa** [comment]
I've sent you a link to our slack channel. Looking forward to assisting you.
